# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Accueil"
  url = "/"
  weight = 10

[[main]]
  name = "Nos livres"
	identifier = "livres"
  url = "livres"
  weight = 20

[[main]]
	name = "Polochon et le lutin"
	parent = "livres"
	url = "livres/polochon"
	weight = 10

[[main]]
	name = "L'essuie-main de l'empereur"
	parent = "livres"
	url = "livres/modus"
	weight = 20

[[main]]
  name = "Contactez-nous"
  url = "contact"
  weight = 30
